### ISSUE TITLE
linkCommandHandler: selection range declarative should surround urlPlaceholder instead of linkText

### ISSUE THREAD

**Issue by jasonbarry** [Resetand/textarea-markdown-editor#1]
When using the link button / keyboard shortcut, I think the more common behavior is to have the text selection select the URL placeholder rather than the text of the link. That way you could select some text, then press ⌘K ⌘V to quickly paste a formatted link. 

For an example, see how GitHub does it: 

![Screenshot 2021-08-13 at 12 32 43](https://user-images.githubusercontent.com/236451/129409702-e538bd19-57b3-42da-b133-434589d22114.gif)

**Comment by Resetand** [comment]
Thanks @jasonbarry, make sense
Merged and published  ([0.1.9](https://www.npmjs.com/package/textarea-markdown-editor))
