### ISSUE TITLE
Migration guide from v0.13 to v1.0.1?

### ISSUE THREAD

**Issue by garciasdos** [Resetand/textarea-markdown-editor#11]
Hello there!

First of all congrats on this amazing package. I've been using it for many projects.

Recently I've been trying to update it but there are a lot of breaking changes in this new major version... Is there any migration guide to update my dependencies? The main problem is the whole new `Cursor.new.ts` that has changed entirely. 

Thank you very much!

**Comment by Resetand** [comment]
Hi, thanks for feedback 
I wrote the release note, and extended it with Cursor API migration guide just now – https://github.com/Resetand/textarea-markdown-editor/releases/tag/v1.0.0

Maybe could be even more useful to checkout the [built-in commands implementations](https://github.com/Resetand/textarea-markdown-editor/blob/master/src/lib/handlers.ts) and [sandbox examples](https://github.com/Resetand/textarea-markdown-editor/tree/master/sandbox/src/examples) (especially [this one](https://github.com/Resetand/textarea-markdown-editor/blob/master/sandbox/src/examples/ImageUpload.tsx))
