### ISSUE TITLE
Problem when try to paste link which contains dashes in domain

### ISSUE THREAD

**Issue by tv-dem** [Resetand/textarea-markdown-editor#12]
HI, really appreciate your library!

I have a little problem with pasting links which we place in aws bucket. when i tried to paste such link https://estenpro690b3423f2e44969b7d04492e910a34e151352-dev.s3.eu-west-2.amazonaws.com/public/15c5f258-9eca-4e46-a7be-7887d63bdaec it caused freez and application didn't work at all. I tried to figure out the problem and realized that when i remove dashes in domain like this https://estenpro690b3423f2e44969b7d04492e910a34e151352dev.s3.euwest2.amazonaws.com/public/15c5f258-9eca-4e46-a7be-7887d63bdaec it works as well

**Comment by Resetand** [comment]
It's taken me a too long time to respond and fixed, sorry 🙃 
Thanks for you feedback. It looks like the problem is with the regular expression. I fixed it by using a built-in `URL` API at #13

**Comment by Resetand** [comment]
Fixes released at [v1.0.2](https://github.com/Resetand/textarea-markdown-editor/releases/tag/v1.0.2)

**Comment by tv-dem** [comment]
Thank you so much! :)
