### ISSUE TITLE
Allow for nested textarea

### ISSUE THREAD

**Issue by austincondiff** [Resetand/textarea-markdown-editor#3]
The custom texarea component I am using ([eact-simple-code-editor](https://github.com/satya164/react-simple-code-editor)) is contained in a div and there is nothing I can do about it. When the child element of the `TextareaMarkdown.Wrapper` component is not a `HTMLTextAreaElement` an error is thrown. This means I cannot use this in my project with syntax highlighting because the `react-simple-code-editor` needs a wrapper div to function. Is it possible to instead traverse the DOM tree and find the first descendant that is a `HTMLTextAreaElement`?

**Comment by Resetand** [comment]
Thanks, fixed in #4

**Comment by Resetand** [comment]
Deployed patch [0.1.11](https://www.npmjs.com/package/textarea-markdown-editor)
