### ISSUE TITLE
Separate Markdown Commands from Textarea

### ISSUE THREAD

**Issue by pspeter3** [Resetand/textarea-markdown-editor#7]
This library looks great! I was wondering though if it's possible to separate the Markdown commands from the text area itself. I think having a library of string operations for Markdown would be really useful.

**Comment by Resetand** [comment]
HI, sorry i hope it's late still relevant. Can you tell a bit more about the problem and maybe give an example of use case?

**Comment by pspeter3** [comment]
No worries! My observation is that this library is really two parts:

1. A set of commands to change markdown strings
2. A library to bind React to those commands

I was curious how you would feel about splitting the library into those two parts.

**Comment by Resetand** [comment]
For now it's seems like all commands implementations are deeply tied on textarea element context such as selection, current position and so on. And this is actually is the most challenging and the most useful part of the library to bind all things together. 
it's hard to imagine how you can use it out of context of textarea for now.
But I will follow the topic and research it more deeply.

**Comment by pspeter3** [comment]
I agree that selection and position are core components. I think the question is what happens if you want to use the Markdown commands for another framework besides React?

**Comment by Resetand** [comment]
it's actually possible since `v1.0.0`
https://github.com/Resetand/textarea-markdown-editor#%CE%B2-usage-without-react

```js
import { bootstrapTextareaMarkdown } from "textarea-markdown-editor/dist/bootstrap";

const textarea = document.querySelector("textarea"); // element can be obtained from anywhere, this is just an example;

const { trigger, dispose } = bootstrapTextareaMarkdown(textarea, {
    options: {}, // optional options config
    commands: [], // optional commands configs
});
```

**Comment by Resetand** [comment]
But as i mentioned

> since the library was originally written to be used with react, your package manager probably will warn you about missing peer-dependencies
